config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  # Defines the root path route ("/")
  get 'home/about'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum :status, { pending: 0, in_progress: 1, done: 2, failed: 3}, default: :pending
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include ActionView::Helpers::TagHelper
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  def about
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  def alert_message(class_name, message)
    content_tag(:div, class: class_name, role: "alert") do
      (message.html_safe) +
      content_tag(:button, "", class: "btn-close", data: { bs_dismiss: "alert" }, aria: { label: "Close" })
    end
  end


  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: alert_message("alert alert-success alert-dismissible fade show", "Tarefa criada com sucesso.") }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: alert_message("alert alert-warning alert-dismissible fade show", "Tarefa atualizada com sucesso.") }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other, notice: alert_message("alert alert-danger alert-dismissible fade show", "Tarefa excluída com sucesso.") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/about.html.erb
<% content_for :title, "Sobre nós..." %>
Sobre nós...

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>FEU SOU MTO LEGAL</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for(:title) || "Todolist" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'todos/navbar' %>
    <div class="container">
      <% if notice%>
        <br/>
        <%= notice.html_safe %>
      <%end%>
      <br/>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div class="mb-3">
      <%= form.label "Título", class: "form-label" %>
      <%= form.text_field :title, class:"form-control",  placeholder: "Insira aqui o título da sua tarefa..." %>
    </div>

    <div class="mb-3">
      <%= form.label "Descrição", class: "form-label" %>
      <%= form.text_area :body, class:"form-control", placeholder: "Insira aqui a descrição da sua tarefa..." %>
    </div>

    <div class="mb-3">
      <%= form.label "Status", class: "form-label" %>
      <%= form.select :status, options_for_select([["Pendente", :pending],["Em progresso", :in_progress],["Feito", :done], ["Cancelada", :failed]]), {}, {:class => "form-select form-select-lg mb-3"} %>
    </div>

    <div class="mb-3">
      <%= form.submit "Criar tarefa", class: "btn btn-success"%>
    </div>
  </form>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'To Do List App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Sobre nós', home_about_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Tarefas', todos_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to 'Nova Tarefa', new_todo_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <button class="btn btn-dark ms-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><span class="navbar-toggler-icon"></span></button>
  </div>
</nav>

<div class="offcanvas offcanvas-end text-bg-dark" data-bs-scroll="true" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Menu de conta</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <% if user_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to 'Editar conta', edit_user_registration_path, class:"btn btn-secondary" %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class:"btn btn-secondary mt-3" %>
      </ul>
    <% else %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to 'Cadastrar-se', new_user_registration_path, class:"btn btn-secondary" %>
        <%= link_to 'Entrar', new_user_session_path, class:"btn btn-secondary mt-3" %>
      </ul>
    <% end %>
  </div>
</div>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>", class="card mb-3" style="max-width: 18rem;">
  <div class="card-header">
    <h5 class="card-title"> <%= todo.title %> </h5>
  </div>
  <div class="card-body">
    <p class="card-text"><%= todo.body %></p>
  </div>
  <ul class="list-group list-group-flush">
    <% case todo.status
        when "pending" %>
        <%= content_tag(:li, 'Pendente', class: "list-group-item bg-warning", id: nil, data: nil) %>
      <% when "in_progress" %>
        <%= content_tag(:li, 'Em progresso', class: "list-group-item bg-primary text-light", id: nil, data: nil) %> 
      <% when "done" %>
        <%= content_tag(:li, 'Feito', class: "list-group-item bg-info text-light", id: nil, data: nil) %>
      <% when "failed" %>
        <%= content_tag(:li, 'Não realizado', class: "list-group-item bg-danger", id: nil, data: nil) %>
    <% end %>
    </li>
  
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2 p-2 g-col-6" role="group" aria-label="First group">
        <%= link_to "Editar", edit_todo_path(@todo), class:"btn btn-warning" %> 
    </div>
    <div class="btn-group mr-2 p-2 g-col-6" role="group" aria-label="Second group">
        <%= button_to "Excluir tarefa", @todo, method: :delete, class:"btn btn-danger" %>
    </div>
  </div>
</div>

app/views/todos/edit.html.erb
<% content_for :title, "Editando tarefa" %>

<h1>Edite esta tarefa</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Mostrar nais detalhes da tarefa", @todo %> |
  <%= link_to "Voltar para tarefas", todos_path %>
</div>

app/views/todos/index.html.erb
<% content_for :title, "Tarefas" %>

<h1>Suas tarefas</h1>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody> 
      <% @todos.each do |todo| %>
      <tr onclick="location.href='todos/<%= todo.id %>'" >
            <td ><%= todo.title %></td>
            <% case todo.status
                when "pending" %>
                <%= content_tag(:td, 'Pendente', class: "list-group-item bg-warning", id: nil, data: nil) %>
              <% when "in_progress" %>
                <%= content_tag(:td, 'Em progresso', class: "list-group-item bg-primary text-light", id: nil, data: nil) %> 
              <% when "done" %>
                <%= content_tag(:td, 'Feito', class: "list-group-item bg-info text-light", id: nil, data: nil) %>
              <% when "failed" %>
                <%= content_tag(:td, 'Não realizado', class: "list-group-item bg-danger", id: nil, data: nil) %>
            <% end %>
            </td>
          </tr>
       <% end %>
    </tbody>
 
</table>

<%= link_to "Nova Tarefa", new_todo_path, class:"btn btn-success" %>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<h1>Nova Tarefa</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Voltar para tarefas", todos_path %>
</div>

app/views/todos/show.html.erb
<div class="row-gap-3">
  <div class="p-2">
    <%= render @todo %>
  </div>
</div>